package com.alphaalexcompany.friendbot

import com.vk.api.sdk.queries.groups.GroupsSetLongPollSettingsQuery

enum class LongPollPermissions(val value: (GroupsSetLongPollSettingsQuery, Boolean) -> GroupsSetLongPollSettingsQuery) {
    MessageNew(GroupsSetLongPollSettingsQuery::messageNew),
    MessageReply(GroupsSetLongPollSettingsQuery::messageReply),
    MessageEdit(GroupsSetLongPollSettingsQuery::messageEdit),
    MessageAllow(GroupsSetLongPollSettingsQuery::messageAllow),
    MessageDeny(GroupsSetLongPollSettingsQuery::messageDeny),
    MessageTypingState(GroupsSetLongPollSettingsQuery::messageTypingState),
    PhotoNew(GroupsSetLongPollSettingsQuery::photoNew),
    PhotoCommentNew(GroupsSetLongPollSettingsQuery::photoCommentNew),
    PhotoCommentEdit(GroupsSetLongPollSettingsQuery::photoCommentEdit),
    PhotoCommentRestore(GroupsSetLongPollSettingsQuery::photoCommentRestore),
    PhotoCommentDelete(GroupsSetLongPollSettingsQuery::photoCommentDelete),
    AudioNew(GroupsSetLongPollSettingsQuery::audioNew),
    VideoNew(GroupsSetLongPollSettingsQuery::videoNew),
    VideoCommentNew(GroupsSetLongPollSettingsQuery::videoCommentNew),
    VideoCommentEdit(GroupsSetLongPollSettingsQuery::videoCommentEdit),
    VideoCommentRestore(GroupsSetLongPollSettingsQuery::videoCommentRestore),
    VideoCommentDelete(GroupsSetLongPollSettingsQuery::videoCommentDelete),
    WallPostNew(GroupsSetLongPollSettingsQuery::wallPostNew),
    WallRepost(GroupsSetLongPollSettingsQuery::wallRepost),
    WallReplyNew(GroupsSetLongPollSettingsQuery::wallReplyNew),
    WallReplyEdit(GroupsSetLongPollSettingsQuery::wallReplyEdit),
    WallReplyRestore(GroupsSetLongPollSettingsQuery::wallReplyRestore),
    WallReplyDelete(GroupsSetLongPollSettingsQuery::wallReplyDelete),
    LikeAdd(GroupsSetLongPollSettingsQuery::likeAdd),
    LikeRemove(GroupsSetLongPollSettingsQuery::likeRemove),
    BoardPostNew(GroupsSetLongPollSettingsQuery::boardPostNew),
    BoardPostEdit(GroupsSetLongPollSettingsQuery::boardPostEdit),
    BoardPostRestore(GroupsSetLongPollSettingsQuery::boardPostRestore),
    BoardPostDelete(GroupsSetLongPollSettingsQuery::boardPostDelete),
    MarketCommentNew(GroupsSetLongPollSettingsQuery::marketCommentNew),
    MarketCommentEdit(GroupsSetLongPollSettingsQuery::marketCommentEdit),
    MarketCommentRestore(GroupsSetLongPollSettingsQuery::marketCommentRestore),
    MarketCommentDelete(GroupsSetLongPollSettingsQuery::marketCommentDelete),
    GroupLeave(GroupsSetLongPollSettingsQuery::groupLeave),
    GroupJoin(GroupsSetLongPollSettingsQuery::groupJoin),
    GroupChangeSettings(GroupsSetLongPollSettingsQuery::groupChangeSettings),
    GroupChangePhoto(GroupsSetLongPollSettingsQuery::groupChangePhoto),
    GroupOfficersEdit(GroupsSetLongPollSettingsQuery::groupOfficersEdit),
    UserBlock(GroupsSetLongPollSettingsQuery::userBlock),
    UserUnblock(GroupsSetLongPollSettingsQuery::userUnblock),
    PollVoteNew(GroupsSetLongPollSettingsQuery::pollVoteNew)
}
